# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.8.1-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-      
      - run:
          name: Install Clojure
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.9.0.397.sh
            chmod +x linux-install-1.9.0.397.sh
            sudo ./linux-install-1.9.0.397.sh
      # run tests!
      - run: script/test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }} 

      - run: .circleci/maybe-deploy.sh
